# Generated by Django 5.2 on 2025-05-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_language_description'),
        ('material_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='topic',
        ),
        migrations.AddField(
            model_name='test',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='material.section'),
            preserve_default=False,
        ),
    ]
