# Generated by Django 5.2 on 2025-05-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
